# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
array1=np.array(range(10))
array1

3. Create a vector with values ranging from 10 to 49

In [ ]:
arr2=np.arange(10,49)

4. Find the shape of previous array in question 3

In [ ]:
np.shape(arr2)

5. Print the type of the previous array in question 3

In [ ]:
arr2.dtype

6. Print the numpy version and the configuration


In [ ]:
print(np.__version__)
print(np.show_config())

7. Print the dimension of the array in question 3


In [ ]:
arr2.ndim

8. Create a boolean array with all the True values

In [13]:
arryb=[True, True, True,  True, True, True, True]
arryb

[True, True, True, True, True, True, True]

9. Create a two dimensional array




In [19]:
array2d= np.arange(15).reshape(3,5)

10. Create a three dimensional array



In [27]:
array3d=np.arange(20).reshape(2,2,5)

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [32]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [42]:
nularr=np.zeros(10, dtype=int)
nularr[4]=1
nularr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [56]:
idmat = np.identity(3, dtype=int)
idmat

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [64]:
arr2= arr.astype(np.float)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [68]:
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

17. Extract all odd numbers from arr with values(0-9)

In [21]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [24]:
arr2=np.where(arr,-1, arr)
arr2

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [84]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr2d=np.ones((3,3),dtype=np.int)
arr2d[:,1]=0
arr2d

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

Difficulty Level **Medium**

In [26]:
arr2d[1,1]=12

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [33]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[:1,:1]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [40]:
arrdim2=np.arange(10).reshape(2,5)
arrdim2[:1,]


array([[0, 1, 2, 3, 4]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [42]:
arrdim2=np.arange(10).reshape(2,5)
arrdim2[1:,1:2]


array([[6]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [43]:
arrdim2=np.arange(10).reshape(2,5)
arrdim2[0:,3:4]

array([[3],
       [8]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [61]:
arrand=np.random.randn(10,10)
print ("{0} max of entire matrix".format(arrand.max()))
print ("{0} min of the entire matrix".format(arrand.min()))

2.7578987500518175 max of entire matrix
-3.4936577753903117 min of the entire matrix


In [75]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c= np.intersect1d(a,b)
c

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [85]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
g= names=='Will' & names=='Joe'

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [98]:
y= np.arange(15, dtype=np.float).reshape(5,3)
y

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [99]:
z= np.arange(16, dtype=np.float).reshape(2,2,4)
z

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [106]:
e=np.arange(10)
e1=np.sqrt(e)
e2=np.where(e1<0.5,0, e1)
e2

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


40. Generate a matrix of 20 random values and find its cumulative sum