# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
a= np.arange(10)
b=a.reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [15]:
arr1= np.arange(10).reshape(2,5)
arr2= np.ones((2,5),dtype=int)
a3= np.vstack((arr1,arr2))
a3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [36]:
arr1= np.arange(10).reshape(2,5)
arr2= np.ones((2,5),dtype=int)
c=np.hstack((arr1,arr2))
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [7]:
q= np.arange(15).reshape(3,5)
w= q.flatten()
w

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [11]:
q= np.arange(15)
q=q.reshape(5,3)
q

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [15]:
e= np.arange(25).reshape(5,5)
e **2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [17]:
f= np.arange(30).reshape(5,6)
f.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [18]:
f.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [21]:
g=np.median(f)
g

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [24]:
np.transpose(f)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [9]:
s= np.arange(16).reshape(4,4)
print(s)
d=s.diagonal()
sum(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [11]:
from numpy.linalg import det
det(s)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [17]:
k= np.arange(10)
print(np.percentile(k, 5))
print(np.percentile(k, 95))

0.45
8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [41]:
x= np.array([1, None, 2, 3, 4, None])
f=[x==None]
f

[array([False,  True, False, False, False,  True])]